REPOSITORY: Add `Package`
MirzayevDeveloper/CountPad pull request #50
Opened 2023-04-06 20:15 UTC by Ulugbek4499

closes #32

2023-04-06 22:21 UTC, Xurshid-A-J requested changes

2023-04-06 22:21 UTC, Xurshid-A-J commented on ConsoleUI/Program.cs
> +﻿using System;
Bring Header file

2023-04-06 22:22 UTC, Xurshid-A-J commented on CountPad.Domain/Models/Packages/Package.cs
> +﻿using System;
Header file here too

2023-04-06 22:23 UTC, Xurshid-A-J commented on CountPad.Domain/Models/Solds/Sold.cs
> +﻿using System;
Header file here too

2023-04-06 22:24 UTC, Xurshid-A-J commented on CountPad.Domain/Models/Users/User.cs
> +﻿using System;
Header

2023-04-06 22:24 UTC, Xurshid-A-J commented on CountPad.Infrastructure/Repositories/BaseRepository.cs
> +﻿using System;
Header

2023-04-06 22:24 UTC, Xurshid-A-J commented on CountPad.Infrastructure/Repositories/PackageRepository.cs
> +
remove extra lines

2023-04-06 22:25 UTC, Xurshid-A-J commented on CountPad.Infrastructure/query.txt
> +
You can remove all enums as we have deleted it already , no need for enum here , they will be as test

2023-04-07 05:14 UTC, MirzayevDeveloper approved these changes
Done!

2023-04-07 07:13 UTC, MirzayevDeveloper commented on CountPad.Domain/Models/Products/ProductTypes.cs
> +using System;
usingdan keyin bitta bush line

2023-04-07 07:13 UTC, MirzayevDeveloper commented on CountPad.Infrastructure/Repositories/PackageRepository.cs
> +
remove extra line

2023-04-07 07:13 UTC, MirzayevDeveloper commented on CountPad.Infrastructure/Repositories/PackageRepository.cs
> +    count DOUBLE PRECISION NOT NULL,
remove it

2023-04-07 07:13 UTC, MirzayevDeveloper commented on CountPad.Infrastructure/Repositories/PackageRepository.cs
> +    count DOUBLE PRECISION NOT NULL,
do code cleanup

2023-04-07 07:20 UTC, merged